// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXS-BPNnsI4X1KmX3-_qiAAeBRzG_J60',
    appId: '1:484697789909:web:5250486374bc2feca5595c',
    messagingSenderId: '484697789909',
    projectId: 'proyecto1-d58a1',
    authDomain: 'proyecto1-d58a1.firebaseapp.com',
    storageBucket: 'proyecto1-d58a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW8yv0lUsuu4P2x0tBZZ-mQ9H33aZEe_4',
    appId: '1:484697789909:android:ba8fce7290a17c18a5595c',
    messagingSenderId: '484697789909',
    projectId: 'proyecto1-d58a1',
    storageBucket: 'proyecto1-d58a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu4g3Bmk9Y_g5BsFLboH0M7QwbIqZTBUE',
    appId: '1:484697789909:ios:c9f29927cace539ba5595c',
    messagingSenderId: '484697789909',
    projectId: 'proyecto1-d58a1',
    storageBucket: 'proyecto1-d58a1.appspot.com',
    iosClientId: '484697789909-j44kdjis93e1hv8hru7v5f1nqbuhd88r.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto117401335',
  );
}
